### ISSUE TITLE
save may fail when drawing large contours

### ISSUE THREAD

**Issue by r03ert0** [neuroanatomy/microdraw#30]
the server will display:

```
PayloadTooLargeError: request entity too large
    at readStream (/var/www/html/microdraw/node_modules/raw-body/index.js:155:17)
    at getRawBody (/var/www/html/microdraw/node_modules/raw-body/index.js:108:12)
    at read (/var/www/html/microdraw/node_modules/body-parser/lib/read.js:77:3)
    at jsonParser (/var/www/html/microdraw/node_modules/body-parser/lib/types/json.js:135:5)
    at Layer.handle [as handle_request] (/var/www/html/microdraw/node_modules/express/lib/router/layer.js:95:5)
    at trim_prefix (/var/www/html/microdraw/node_modules/express/lib/router/index.js:317:13)
    at /var/www/html/microdraw/node_modules/express/lib/router/index.js:284:7
    at Function.process_params (/var/www/html/microdraw/node_modules/express/lib/router/index.js:335:12)
    at next (/var/www/html/microdraw/node_modules/express/lib/router/index.js:275:10)
    at expressInit (/var/www/html/microdraw/node_modules/express/lib/middleware/init.js:40:5)
```

**Comment by r03ert0** [comment]
fixed in commit c7124ff63d01e57fb9002798846cb190e4d259c8, increasing bodyParse limit
