### ISSUE TITLE
MicroDraw falls back to old wrong version of node after restart, and crashes

### ISSUE THREAD

**Issue by katjaq** [neuroanatomy/microdraw#64]
For some reason, MicroDraw restarted and went back to using the wrong version of node. This causes a complete crash of MicroDraw (service unavailable).

Can we make sure that in case of restart MicroDraw automatically uses the correct version of node? @ntraut @dhovart

error log:

```
0|microdra | 2022-03-08 12:01:11.874: /var/www/html/microdraw/node_modules/neuroweblab/accessControl/AccessControlService.js:8
0|microdra | 2022-03-08 12:01:11.874:   static #hasAccess(accessType, requestedAccessLevel, project, userId) {
0|microdra | 2022-03-08 12:01:11.874:                    ^
0|microdra | 2022-03-08 12:01:11.874: 
0|microdra | 2022-03-08 12:01:11.874: SyntaxError: Unexpected token '('
0|microdra | 2022-03-08 12:01:11.874:     at Module._compile (internal/modules/cjs/loader.js:895:18)
0|microdra | 2022-03-08 12:01:11.874:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
0|microdra | 2022-03-08 12:01:11.874:     at Module.load (internal/modules/cjs/loader.js:815:32)
0|microdra | 2022-03-08 12:01:11.874:     at Function.Module._load (internal/modules/cjs/loader.js:727:14)
0|microdra | 2022-03-08 12:01:11.874:     at Module.require (internal/modules/cjs/loader.js:852:19)
0|microdra | 2022-03-08 12:01:11.874:     at Module.Hook._require.Module.require (/home/rto/.npm-global/lib/node_modules/pm2/node_modules/require-in-the-middle/index.js:80:39)
0|microdra | 2022-03-08 12:01:11.874:     at require (internal/modules/cjs/helpers.js:74:18)
0|microdra | 2022-03-08 12:01:11.874:     at Object.<anonymous> (/var/www/html/microdraw/node_modules/neuroweblab/accessControl/index.js:3:30)
0|microdra | 2022-03-08 12:01:11.874:     at Module._compile (internal/modules/cjs/loader.js:959:30)
0|microdra | 2022-03-08 12:01:11.874:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:995:10)
```

**Comment by katjaq** [comment]
As for now, this seems to be solved :) Thank you @ntraut . So in future, we just need to keep in mind to run install and save when we upgrade mongo again. So I will close the issue.
